name: Windows builds

on: [push, pull_request]

jobs:
  build_windows_vs:
    name: ${{ matrix.conf.name }}
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || contains('dreamer,kcgen,ant-222,Wengier', github.actor) == false
    strategy:
      matrix:
        conf:
          - name: MSVC 32-bit
            arch: x86
            vs-platform: x86
            vcpkg-triplet: x86-windows
          - name: MSVC 64-bit
            arch: x64
            vs-platform: x64
            vcpkg-triplet: x64-windows
    steps:
      - uses:  actions/checkout@v2
      - name:  Install packages
        shell: pwsh
        run: |
          vcpkg install --triplet ${{ matrix.conf.vcpkg-triplet }} libpng sdl2 sdl2-net opusfile
          vcpkg integrate install
      - name:  Log environment
        shell: pwsh
        run:   .\scripts\log-env.ps1
      - name:  Build
        shell: pwsh
        env:
          PATH: '${env:PATH};C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64'
        run: |
          cd vs
          MSBuild -m dosbox.sln -p:Configuration=Debug -p:Platform=${{ matrix.conf.vs-platform }} | Tee-Object build.log


  build_windows_vs_release:
    name: ${{ matrix.conf.name }}
    runs-on: windows-latest
    if: github.event_name != 'pull_request' || contains('dreamer,kcgen,ant-222,Wengier', github.actor) == false
    strategy:
      matrix:
        conf:
          - name: Release build (32-bit)
            vcpkg-triplet: x86-windows
            vs-platform: x86
            vs-release-dirname: Win32
          - name: Release build (64-bit)
            vcpkg-triplet: x64-windows
            vs-platform: x64
            vs-release-dirname: x64
    steps:
      - uses:  actions/checkout@v2
      - name:  Install packages
        shell: pwsh
        run: |
          vcpkg install --triplet ${{ matrix.conf.vcpkg-triplet }} libpng sdl2 sdl2-net opusfile
          vcpkg integrate install
      - name:  Log environment
        shell: pwsh
        run:   .\scripts\log-env.ps1
      - name:  Inject version string
        shell: bash
        run: |
          set -x
          git fetch --prune --unshallow
          export VERSION=$(git describe --abbrev=4)
          sed -i "s|VERSION \"git\"|VERSION \"$VERSION\"|" src/platform/visualc/config.h
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name:  Build
        shell: pwsh
        env:
          PATH: '${env:PATH};C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64'
        run: |
          cd vs
          MSBuild -m dosbox.sln -p:Configuration=Release -p:Platform=${{ matrix.conf.vs-platform }}
      - name:  Package
        shell: bash
        env:
          VC_REDIST_PATH: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Redist/MSVC'
        run: |
          set -x

          # Prepare content
          readonly RELEASE_DIR=${{ matrix.conf.vs-release-dirname }}/Release
          mkdir -p dest/doc
          cp vs/$RELEASE_DIR/dosbox.exe           dest/
          cp COPYING                              dest/COPYING.txt
          cp docs/README.template                 dest/README.txt
          cp docs/README.video                    dest/doc/video.txt
          cp docs/vc_redist.txt                   dest/doc/vc_redist.txt
          cp README                               dest/doc/manual.txt
          cp vs/$RELEASE_DIR/libpng16.dll         dest/
          cp vs/$RELEASE_DIR/ogg.dll              dest/
          cp vs/$RELEASE_DIR/opus.dll             dest/
          cp vs/$RELEASE_DIR/SDL2.dll             dest/
          cp vs/$RELEASE_DIR/SDL2_net.dll         dest/
          cp src/libs/zmbv/$RELEASE_DIR/zlib1.dll dest/
          cp src/libs/zmbv/$RELEASE_DIR/zmbv.dll  dest/

          # List version of available Visual C++ Redistributable files
          ls -l "$VC_REDIST_PATH"

          # Include the necessary dlls from one of available versions
          readonly VC_REDIST_VERSION="14.27.29016"
          readonly VC_REDIST_DIR="$VC_REDIST_PATH/$VC_REDIST_VERSION/${{ matrix.conf.arch }}/Microsoft.VC142.CRT"
          cp "$VC_REDIST_DIR/msvcp140.dll"       dest/
          cp "$VC_REDIST_DIR/vcruntime140.dll"   dest/
          cp "$VC_REDIST_DIR/vcruntime140_1.dll" dest/ || true # might be missing, depending on arch

          # Fill README template file
          sed -i "s|%GIT_COMMIT%|$GITHUB_SHA|"               dest/README.txt
          sed -i "s|%GIT_BRANCH%|${GITHUB_REF#refs/heads/}|" dest/README.txt
          sed -i "s|%GITHUB_REPO%|$GITHUB_REPOSITORY|"       dest/README.txt

          # Create dir for zipping
          mv dest dosbox-staging-windows-${{ matrix.conf.vs-platform }}-${{ env.VERSION }}

      - name: Windows Defender AV Scan
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          $dosboxDir = "${{ github.workspace }}\dosbox-staging-windows-${{ matrix.conf.vs-platform }}-${{ env.VERSION }}"
          & 'C:\Program Files\Windows Defender\MpCmdRun.exe' -Scan -ScanType 3 -DisableRemediation -File $dosboxDir
          if( $LASTEXITCODE -ne 0 ) {
              Get-Content -Path $env:TEMP\MpCmdRun.log
              Throw "Exit $LASTEXITCODE : Windows Defender found an issue"
          }

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: dosbox-staging-windows-${{ matrix.conf.vs-platform }}-${{ env.VERSION }}
          path: dosbox-staging-windows-${{ matrix.conf.vs-platform }}-${{ env.VERSION }}
